# Metadata
name: CI
# Steps for CI : tests → build img Docker

permissions:
  actions: read
  contents: read

# Event that triggers the workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Define the jobs
jobs:
  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name : Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install deps
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Run unit tests
        run: npm run test -- --run
      - name: Build frontend
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
        run: npm run build
